import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/navbar";
import Footer from "./components/footer/footer";


const poppins = Poppins({ subsets: ["latin"], weight: ["200","100","300","400","500","600","700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body className={poppins.className}>
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
